language: java
jdk:
- oraclejdk8

env:
  matrix:
  - VERSION=1.2.3

install: mvn install

script: 
  - docker build -t drivereu/after-action-review:latest -t drivereu/after-action-review:$VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push drivereu/after-action-review

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
