export default {
  LOG: "Log",
  INVITE: "TopicInvite",
  ALERT: "Alert",
  GEO_JSON: "GeoJSONEnvelope",
  FEATURE_COLLECTION: "FeatureCollection",
  LARGE_DATA_UPDATE: "LargeDataUpdate",
  ROLE_PLAYER_MESSAGE: "RolePlayerMessage",
  OBSERVER_TOOL_ANSWER: "ObserverToolAnswer",
  SESSION_MGMT: "SessionMgmt",
  REQUEST_CHANGE_OF_TRIAL_STATE: "RequestChangeOfTrialStage",
  REQUEST_START_INJECT: "RequestStartInject",
  POST_MESSAGE: "Post",
  MAP_LAYER_UPDATE: "MapLayerUpdate",
}
